extends Node

const CLIENT_VIEW_ABOUT = "CLIENT_VIEW_ABOUT"
const CLIENT_VIEW_INSTRUCTIONS = "CLIENT_VIEW_INSTRUCTIONS"
const CLIENT_VIEW_SETTINGS = "CLIENT_VIEW_SETTINGS"
const CLIENT_VIEW_MAIN_MENU = "CLIENT_VIEW_MAIN_MENU"
const CLIENT_VIEW_NONE = "CLIENT_VIEW_NONE"
const CLIENT_VIEW_GAME_OVER = "CLIENT_VIEW_GAME_OVER"
